theme: jekyll-theme-cayman

name: Rileys Blog

# Short bio or description (displayed in the header)
description: My blog. I write about nerdy stuff. Keyboards and programming mostly.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/60358181?s=60&v=4%22
